
-- إضافة عمود إعدادات الحالات المستقلة
ALTER TABLE public.billboard_print_customization
  ADD COLUMN IF NOT EXISTS status_overrides jsonb DEFAULT '{
    "normal": {},
    "no-design": {
      "main_image_top": "90mm",
      "main_image_left": "50%",
      "main_image_width": "120mm",
      "main_image_height": "140mm",
      "installed_images_top": "88mm",
      "installed_images_left": "50%",
      "installed_images_width": "180mm",
      "installed_images_gap": "5mm",
      "installed_image_height": "80mm",
      "designs_top": "178mm",
      "designs_left": "16mm",
      "designs_width": "178mm",
      "designs_gap": "10mm",
      "design_image_height": "42mm",
      "status_badges_top": "75mm",
      "status_badges_left": "50%",
      "status_badges_font_size": "11px"
    },
    "one-design": {
      "main_image_top": "90mm",
      "main_image_left": "50%",
      "main_image_width": "120mm",
      "main_image_height": "140mm",
      "installed_images_top": "88mm",
      "installed_images_left": "50%",
      "installed_images_width": "180mm",
      "installed_images_gap": "5mm",
      "installed_image_height": "80mm",
      "designs_top": "178mm",
      "designs_left": "16mm",
      "designs_width": "178mm",
      "designs_gap": "10mm",
      "design_image_height": "42mm",
      "status_badges_top": "75mm",
      "status_badges_left": "50%",
      "status_badges_font_size": "11px"
    },
    "one-face": {
      "main_image_top": "90mm",
      "main_image_left": "50%",
      "main_image_width": "120mm",
      "main_image_height": "140mm",
      "installed_images_top": "88mm",
      "installed_images_left": "50%",
      "installed_images_width": "180mm",
      "installed_images_gap": "5mm",
      "installed_image_height": "80mm",
      "designs_top": "178mm",
      "designs_left": "16mm",
      "designs_width": "178mm",
      "designs_gap": "10mm",
      "design_image_height": "42mm",
      "status_badges_top": "75mm",
      "status_badges_left": "50%",
      "status_badges_font_size": "11px"
    },
    "with-cutout": {
      "main_image_top": "90mm",
      "main_image_left": "50%",
      "main_image_width": "120mm",
      "main_image_height": "140mm",
      "installed_images_top": "88mm",
      "installed_images_left": "50%",
      "installed_images_width": "180mm",
      "installed_images_gap": "5mm",
      "installed_image_height": "80mm",
      "designs_top": "178mm",
      "designs_left": "16mm",
      "designs_width": "178mm",
      "designs_gap": "10mm",
      "design_image_height": "42mm",
      "status_badges_top": "75mm",
      "status_badges_left": "50%",
      "status_badges_font_size": "11px"
    }
  }'::jsonb;
